{{- if .Values.gnbConfig.remote_control.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "srsran-gnb.fullname" . }}-metrics
  labels:
    {{- include "srsran-gnb.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "srsran-gnb.selectorLabels" . | nindent 4 }}
  ports:
    - name: websocket
      port: {{ .Values.gnbConfig.remote_control.port }}
      targetPort: {{ .Values.gnbConfig.remote_control.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
