apiVersion: v2
name: srsran-gnb
description: srsRAN gNB Helm Chart
kubeVersion: ">= 1.24.0-0"
icon: https://docs.srsran.com/en/latest/_static/logo.png
home: https://docs.srsran.com/projects/project/en/latest/
sources:
- https://github.com/srsran/srsran_project
keywords:
- srsran
- 5g
- oran
- vran
- gnb
- mobile
type: application
version: 1.0.0
appVersion: "25.04"